openapi: 3.0.3

info:
  title: To do List
  version: 0.0.1

servers:
  - url: /api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Wish:
      description: 許願小卡
      type: object
      required:
        - id
        - message
      properties:
        id:
          type: integer
          readOnly: true
          minimum: 1
        message:
          type: string
    User:
      description: 使用者
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          readOnly: true
          minimum: 1
        email:
          type: string
          format: email
    PaginationResponse:
      description: Columns of pagination
      type: object
      properties:
        current_page:
          type: integer
          readOnly: true
          minimum: 1
        per_page:
          type: integer
          readOnly: true
          minimum: 1
          default: 10
        from:
          type: integer
          readOnly: true
          minimum: 1
          nullable: true
        to:
          type: integer
          readOnly: true
          minimum: 1
          nullable: true
        last_page:
          type: integer
          readOnly: true
          minimum: 1
        total:
          type: integer
          readOnly: true
          minimum: 0
        first_page_url:
          type: string
          readOnly: true
        prev_page_url:
          type: string
          readOnly: true
          nullable: true
        next_page_url:
          type: string
          readOnly: true
          nullable: true
        last_page_url:
          type: string
          readOnly: true

  parameters:
    idPath:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: The ID of data in API path
    limit:
      in: query
      name: limit
      schema:
        type: integer
      description: The count of each page
    page:
      in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
      description: Which page to retrieve

paths:
  /hello:
    get:
      summary: Example API
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - hello_world
                properties:
                  hello_world:
                    type: string

  /v1/auth/signup:
    post:
      summary: Signup a new account
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "422":
          description: invalid input

  /v1/auth/login:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: 1|JIKEXqx1xYmM66UeDEE3LDbRRz0ooPSjYhTPTCQD
        "401":
          description: Unauthenticated
        "404":
          description: Not Found
        "422":
          description: Invalid input

  /v1/wishes:
    get:
      summary: 許願小卡列表 (分頁)
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [draft, submitted]
          description: 送出狀態
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "#/components/schemas/PaginationResponse"
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Wish"
        "401":
          description: Unauthenticated

    post:
      summary: 新增一張許願小卡
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Wish"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
        "401":
          description: Unauthenticated
        "422":
          description: Invalid input

  /v1/wishes/{id}:
    get:
      summary: 指定的許願小卡資料
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idPath"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
        "401":
          description: Unauthenticated
        "404":
          description: Not Found

    put:
      summary: 修改許願小卡
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idPath"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Wish"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
        "401":
          description: Unauthenticated
        "404":
          description: Not Found
        "422":
          description: Invalid input

    delete:
      summary: 刪除許願小卡
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idPath"
      responses:
        "200":
          description: ok
        "401":
          description: Unauthenticated
        "404":
          description: Not Found

  /v1/wishes/{id}/submit:
    post:
      summary: 送出指定的許願小卡
      tags:
        - 許願小卡
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/idPath"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wish"
        "401":
          description: Unauthenticated
        "404":
          description: Not Found

